spring:
  datasource:
    url: "jdbc:mysql://15.165.16.65:3306/testdb?useSSL=true&characterEncoding=UTF-8&serverTimezone=UTC"
#    url: "jdbc:mysql://localhost/testdb"
    username: "kics"
    password: "111111"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    database: mysql

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


#
#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: "jdbc:mysql://localhost:3306/testdb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
#    username: "root"
#    password: '111111'
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: "jdbc:mysql://localhost/testdb"
#    username: "root"
#    password: "111111"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect